version: '3.8'

services:
  wordpress:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ${PWD}/wordpress_data:/var/www/html

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - ${PWD}/db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
